### ISSUE TITLE
Update scheme for minislate's kubernetes binaries

### ISSUE THREAD

**Issue by Mansalu** [slateci/minislate#29]
Currently Kubernetes binary versions are hard coded in minislate. We need to determine an efficient scheme for automatically updating when appropriate. The SLATE API Kubernetes version must also be considered here.

Currently this is in the dockerfile:

```
kubelet=1.14.0-00 
kubeadm=1.14.0-00 
kubectl=1.14.0-00
```

Hyperkube was also hard coded at `v1.14.0`, but it has been removed in the `nobuild` branch.

We must adhere to:

https://kubernetes.io/docs/setup/release/version-skew-policy/

**Comment by sthapa** [comment]
I don't think this is an issue at this point.  I don't see this hard coded into the dockerfiles anymore.
